CREATE TABLE IF NOT EXISTS f1_bot (
    id SERIAL PRIMARY KEY,
    chat_id BIGINT UNIQUE NOT NULL,
    is_subscribe BOOLEAN DEFAULT TRUE,
    time_reg TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Samara')
);